version: '3'

services:
  selenium-chrome:
    image: selenium/standalone-chrome:91.0
    ports:
        - "4444:4444"
        - "5900:5900"

  jupyter:
    build: ./build/jupyter/
    ports:
        - "8888:8888"
    volumes:
        - ".:/home/jovyan/work"
    depends_on:
        - selenium-chrome
